### ISSUE TITLE
Package AiForms.Maui.SettingsView 0.1.10-pre is not compatible with net6.0

### ISSUE THREAD

**Issue by tranb3r** [muak/AiForms.Maui.SettingsView#2]
I'm currently migrating my Xamarin.Forms app to Maui.

The architecture of my app looks like this: ios/android app -> UI library -> Core library
- ios/android app projects hold the platform specific code required to start the app
- UI library holds the UI code (pages, view)
- Core libreary holds the business logic code (view models, services, models...)

In the Xamarin app, both UI and Core libraries are netstandard projects.
The UI library references the AiForms.SettingsView package (since it suports the netstandard TFM).

In my Maui app, both UI and Core libraries are net6.0 projects.
However I find it impossible to reference the AiForms.Maui.SettingsView package in the UI library.
It expects a net6.0-android / net6.0-ios TFM. 
But there is no reason for that, since this is a cross-platform library, with no specific code to compile.
```
Error	NU1202	
Package AiForms.Maui.SettingsView 0.1.10-pre is not compatible with net6.0 (.NETCoreApp,Version=v6.0). 
Package AiForms.Maui.SettingsView 0.1.10-pre supports:
  - net6.0-android26.0 (.NETCoreApp,Version=v6.0)
  - net6.0-ios13.0 (.NETCoreApp,Version=v6.0)
```

Could you please make sure this package can be installed in a net6.0 project?

Thanks

**Comment by muak** [comment]
@tranb3r 

Thanks for your report.

SettingsView is designed to be referenced by MAUI projects.
So referencing from MAUI is not a problem.

It is certainly not net6.0 compatible, so you may not be able to reference it outside of a MAUI project.

If we make it compatible with net6.0, it will increase the dummy code, so we do not support it, but we would like to consider it.

Thanks.

**Comment by tranb3r** [comment]
I'm not sure I understand your answer.
What is a MAUI project, according to you? 
My UI library targets net6.0 and uses maui. It's perfectly ok, since there is no platform specific code in my library, and as long as it's referenced by a MAUI application at some point (targeting net6.0-android or net6.0-ios).
Besides, all the MAUI plugins I'm using target net6.0 (as well as net6.0-android and net6.0-ios), in order to make sure they can be referenced by libraries. For example, CommunityToolkit.Maui, Mopups, Syncfusion.Maui.* ... they all work without having to target android/ios in a library.
Also, why did you change what was working with the xamarin.forms version of your plugin, which supported targeting netstandard?
Of course, I'm assuming it's only a minor change in the csproj and nuspec. Why do you think it would add a lot of 'dummy code' to support it ?

**Comment by muak** [comment]
@tranb3r 

I corresponded it.
Thanks.

**Comment by tranb3r** [comment]
Thanks. It builds so I guess it works.
However, I can't update because of another issue. #5
