### ISSUE TITLE
[iOS] [NET9] [MAUI] TypeLoadException `ShellScrollViewTracker` not found

### ISSUE THREAD

**Issue by dmariogatto** [muak/AiForms.Maui.SettingsView#37]
### Description

Install latest package [1.0.15](https://www.nuget.org/packages/AiForms.Maui.SettingsView/1.0.15) into a .NET9 MAUI project and it will throw a `System.TypeLoadException` on startup.

This is because the `ShellScrollViewTracker` has been removed from .NET9, it was previously marked as obsolete with the notice `"Scrolling is now handled by KeyboardAutoManagerScroll."`.

### Steps to Reproduce

1. Create new .NET9 MAUI project
2. Install SettingsView
3. Launch application

### Expected Behavior

Does not crash at startup.

### Actual Behavior

Throws `System.TypeLoadException` on application startup.

```
Exception has occurred: CLR/System.TypeLoadException
An unhandled exception of type 'System.TypeLoadException' occurred in Microsoft.iOS.dll: 'Could not load type of field 'AiForms.Settings.Platforms.iOS.KeyboardInsetTracker:_shellScrollViewTracker' (6) due to: Could not resolve type with token 0100012c from typeref (expected class 'Microsoft.Maui.Controls.Handlers.Compatibility.ShellScrollViewTracker' in assembly 'Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:Microsoft.Maui.Controls.Handlers.Compatibility.ShellScrollViewTracker member:(null)'
   at UIKit.UIApplication.xamarin_UIApplicationMain(Int32 argc, IntPtr argv, IntPtr principalClassName, IntPtr delegateClassName, IntPtr* gchandle)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
```

### Platforms

- [ ] Android
- [X] iOS

### Basic Information

- AiForms.SettingsView 1.0.15
- MAUI 9.0.12
- Android Support Library Version: N/A
- Affected Devices: iOS

### Screenshots

N/A

### Reproduction Link

N/A

### Workaround

N/A

**Comment by dmariogatto** [comment]
It doesn't look like the `ShellScrollViewTracker` is initialised in [KeyboardInsetTracker](https://github.com/muak/AiForms.Maui.SettingsView/blob/64f401c6474c1606d8336eed4fd3cad9f3fbf45a/SettingsView/Native/iOS/KeyboardInsetTracker.cs#L24C28-L24C51), so I assume it can be safely removed without introducing any new issues.

**Comment by muak** [comment]
@dmariogatto 
Thank you for your report.
I have removed the ``ShellScrollViewTracker`` in ver. 1.0.16.
Please try it once.

**Comment by dmariogatto** [comment]
That was a quick fix! Thank you @muak 👍
